name: Build Custom Arch ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Arch container
        run: |
          docker run --privileged -v ${{ github.workspace }}:/work archlinux:latest /bin/bash -c "

          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso git

          cd /work

          git clone https://gitlab.archlinux.org/archlinux/archiso.git
          cp -r archiso/configs/releng myiso

          cp packages.x86_64 myiso/packages.x86_64

          mkarchiso -v myiso
          "

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: arch-custom
          path: out/*.iso
